### ISSUE TITLE
Timeseries plots

### ISSUE THREAD

**Issue by glentner** [JeroenDelcour/tplot#22]
I've been playing with `tplot` for a few days now building a command-line tool to show some usage data, basically I've created a CLI connecting `pandas.read_csv` to `tplot`. This has turned out really well and the plots look great in the terminal.

Any thoughts on the best way to handle timeseries/datetime on the x-axis? One approach might be for the user to just cast the timestamps to Unix epoch times, but that's not very human readable on the axis labels. Do you have any sense of how much of a challenge it would be to construct a label formatter on the x-axis to show dates and times nicely (like months+days, or hours+minutes)?

Just sharing ideas, thanks.

**Comment by glentner** [comment]
Right now I'm just forcing parsed date times to unix epochs in seconds and let you scale by day/hour/min in either direction as an offset. This isn't ideal though, it would be awesome to have x-axis labels properly deal in dates, etc.

![Screen Shot 2022-03-03 at 4 46 34 PM](https://user-images.githubusercontent.com/8965948/156658016-314d8956-8906-4785-9c3a-7655d48a7bc5.png)

**Comment by JeroenDelcour** [comment]
That's definitely a good suggestion! Shouldn't be too difficult to handle Datetime objects properly (scaling using epoch time and labeling with human-readable text). I'll try to have a look at it in the next week or so.

Also: wonderful to see tplot being used for cool stuff, that figure looks great!

**Comment by glentner** [comment]
Progress continues on a better interface. I think with good time series labeling this could look really great.

![Screen Shot 2022-03-08 at 6 29 49 PM](https://user-images.githubusercontent.com/8965948/157343332-c5eeb833-d095-4e45-8fd0-dedbb8e95bfe.png)

![Screen Shot 2022-03-08 at 6 34 35 PM](https://user-images.githubusercontent.com/8965948/157343829-1a3aed1e-c9bf-42a6-b8fe-8f3428fb0fb5.png)

![Screen Shot 2022-03-08 at 6 55 31 PM](https://user-images.githubusercontent.com/8965948/157345789-35573cdb-57f7-40fc-8950-b21fbe940b1c.png)

**Comment by JeroenDelcour** [comment]
Handling datetime objects is more difficult than I thought. I figured I could just use epoch timestamps to plot everything as numbers and show the datetime as a string for the axis tick labels, but that beaks the assumption that tick labels and their values are the same - something that is pretty fundamental to how tplot is set up.

There's also the issue of the interval between ticks. tplot creates ticks at round(ish) intervals like 1, 2, 5, 10, 20, 50, 100, etc. This doesn't work for a lot of situations with datetimes: tplot might decide on a 100 000 second tick interval, which is a nice round number in seconds (and epoch timestamps are in seconds), but measured in days that's roughly 1.1574074 - yuck! Depending on what timescale you're plotting, tick intervals end up looking arbitrary. And then there's units of time that have a variable length, such as months or years (leap days). [Time is complicated.](https://www.youtube.com/watch?v=-5wpm-gesOY)

Maybe there are existing open source implementations for getting an appropriate time interval given a set of dates and times, and solutions for any other peculiarities that come up. But unless there's significant interest from a lot of people, I don't think it's worth trying to support datetime objects. It could potentially add a lot of complexity, and I'd like to keep tplot simple.

Your current solution of converting datetimes to a manually chosen time interval (e.g. number of days) seems like the best approach. If you really need to handle datetime objects with all the complexity they bring, there are enough feature-rich plotting libraries out there that can do pretty much whatever you want, including plotting date intervals nine ways to Sunday.

Sorry to get your hopes up!
